#ifndef _FIWIX_MULTIBOOT2_H
#define _FIWIX_MULTIBOOT2_H

/* Multiboot2 magic values */
#define MULTIBOOT2_HEADER_MAGIC        0xE85250D6
#define MULTIBOOT2_BOOTLOADER_MAGIC    0x36D76289
#define MULTIBOOT_ARCHITECTURE_I386    0

#endif /* _FIWIX_MULTIBOOT2_H */
